# Generated by Django 4.2 on 2023-10-19 22:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_anchor_modeling.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessBuyProductTie',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='ID must be alphanumeric, underscores, hyphens, and dots.', regex='^[0-9a-zA-Z_.-]+$')])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to='orders.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_by', to='orders.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSeller',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='products', serialize=False, to='orders.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.business')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineItemProduct',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='line_items', serialize=False, to='orders.orderlineitem')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineItemOrder',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='line_items', serialize=False, to='orders.orderlineitem')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
