# Generated by Django 4.2.6 on 2023-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion
import django_anchor_modeling.fields
import django_anchor_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anchor_modeling', '0001_initial'),
        ('orders', '0008_productstockquantity_productname_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='description', serialize=False, to='orders.tproduct'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='name', serialize=False, to='orders.tproduct'),
        ),
        migrations.AlterField(
            model_name='productstockquantity',
            name='anchor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='stock_quantity', serialize=False, to='orders.tproduct'),
        ),
        migrations.CreateModel(
            name='HistorizedTProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.tproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedProductStockQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(max_length=8)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.productstockquantity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.productname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedProductDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.productdescription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
