# Generated by Django 4.2.6 on 2023-10-30 09:45

from django.db import migrations, models
import django_anchor_modeling.fields
import django_anchor_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anchor_modeling', '0001_initial'),
        ('orders', '0009_alter_productdescription_anchor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithNoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
