# Generated by Django 4.2.6 on 2023-10-30 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_anchor_modeling.fields
import django_anchor_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anchor_modeling', '0001_initial'),
        ('orders', '0010_productwithnohistory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tproduct',
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='historizedtproduct',
            name='business_identifier',
            field=django_anchor_modeling.fields.BusinessIdentifierField(max_length=255),
        ),
        migrations.CreateModel(
            name='WithFKThatSetRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('some_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='some_product', to='orders.tproduct')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHasSeller',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='product', serialize=False, to='orders.tproduct')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='some_value', to='orders.withfkthatsetrelatedname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedWithFKThatSetRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.withfkthatsetrelatedname')),
                ('some_fk', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.tproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedProductHasSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.producthasseller')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.withfkthatsetrelatedname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
