# Generated by Django 4.2.6 on 2023-10-30 16:32

from django.db import migrations, models
import django.db.models.deletion
import django_anchor_modeling.fields
import django_anchor_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anchor_modeling', '0001_initial'),
        ('orders', '0010_productwithnohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithFKThatSetRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('some_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='some_product', to='orders.tproduct')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedWithFKThatSetRelatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.withfkthatsetrelatedname')),
                ('some_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historized_some_product', to='orders.tproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
