# Generated by Django 4.2.6 on 2023-11-13 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_anchor_modeling.fields
import django_anchor_modeling.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_anchor_modeling', '0001_initial'),
        ('orders', '0014_alter_producthasseller_anchor_tbusiness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Grandchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Grandparent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255, unique=True)),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('filters', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ChildName',
            fields=[
                ('value', models.CharField(max_length=100)),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='name', serialize=False, to='orders.child')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChildParent',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='%(class)s_set', serialize=False, to='orders.child')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandchildName',
            fields=[
                ('value', models.CharField(max_length=100)),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='name', serialize=False, to='orders.grandchild')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandchildParent',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='%(class)s_set', serialize=False, to='orders.grandchild')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrandparentName',
            fields=[
                ('value', models.CharField(max_length=100)),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='name', serialize=False, to='orders.grandparent')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.parent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedGrandparent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_identifier', django_anchor_modeling.fields.BusinessIdentifierField(max_length=255)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.grandparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedGrandchild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.grandchild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentParent',
            fields=[
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='%(class)s_set', serialize=False, to='orders.parent')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.grandparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentName',
            fields=[
                ('value', models.CharField(max_length=100)),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='name', serialize=False, to='orders.parent')),
                ('transaction', models.ForeignKey(default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=models.SET(django_anchor_modeling.models.Transaction.get_sentinel), to='django_anchor_modeling.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedParentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.grandparent')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.parentparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedParentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.parentname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedGrandparentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.grandparentname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedGrandchildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.child')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.grandchildparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedGrandchildName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.grandchildname')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedChildParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('value', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='orders.parent')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.childparent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorizedChildName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('off_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deactivated_%(app_label)s_%(class)ss', related_query_name='that_deactivated_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('on_txn', models.ForeignKey(db_constraint=False, default=django_anchor_modeling.models.Transaction.get_sentinel_id, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(app_label)s_%(class)ss', related_query_name='that_created_%(app_label)s_%(class)ss', to='django_anchor_modeling.transaction')),
                ('original', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='versions', to='orders.childname')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
